### ISSUE TITLE
Mantling

### ISSUE THREAD

**Issue by cullenbohannon** [oivio/ALS_Component#1]
Hi, thanks for sharing this, it's amazing work!

Just a bit of feedback:
- trying to mantle on the wall close to the AI teleports the player in a different place on the same axis
- AI doesn't follow the character, (I assume that logic from ALS was probably not ported over, but thought I would mention)
- When running and rolling (double press ALT), the player remains crouched
- The FP camera (C hold) is probably not implemented (yet - ADS mode looks good tho) - not sure if there is a plan to make a FP camera as well

Hope it helps to keep developing this further!

**Comment by oivio** [comment]
- there is a strange issue with the current mantle system I did temporarily did fix ( v0.52) it but, in the end, I will overall change it and it will include climbing
-  yes, at this moment my main focus is to have the player fully working then I will work on AI.
- I did add a fix v0.52
- FPS camera has been added v0.52

I really do appreciate the feedback
