### ISSUE TITLE
Mantling (different bug)

### ISSUE THREAD

**Issue by cullenbohannon** [oivio/ALS_Component#2]
**Detailed description of issue**
The foot position changes after mantling

**Steps To Reproduce:**
1: Switch to sword and shield for example
2: Attempt to climb the stacked boxes
3: You'll notice every time the left leg either jumps in place or  remain in a weird position

**Expected Results:**
Seamless mantling

**Actual Results:**
Foot is in a weird position, with the knee bent in 8 out of 10 times
![Desktop Screenshot 2021 07 05 - 22 34 59 01 (2)](https://user-images.githubusercontent.com/65356707/124519719-03bd0a00-dde2-11eb-93db-7d1372c03182.png)

Hope it helps!
Update - it seems like a shield and sword issue, as weird foot behaviour happens when strafing (left/right) or even moving forward and stopping as well.

**Comment by oivio** [comment]
Thank you. 
Probably curves inside shield and sword walk animation need a bit of adjusting or need just to find better animations for it.
